//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priiil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aut
    {
        public int ID_Aut { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int ID_Dolznosti { get; set; }
    
        public virtual Dolznosti Dolznosti { get; set; }
    }
}
