//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priiil
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichnayaZayavka
    {
        public int ID { get; set; }
        public string Tsel_posecheniya { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public string FIO { get; set; }
        public string Podrazdelenie { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Dadname { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Seriya { get; set; }
        public string Number { get; set; }
        public byte[] Photo { get; set; }
        public string Status { get; set; }
    }
}
