//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priiil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisok_Zayavok
    {
        public int ID_Zayavki { get; set; }
        public string Tip_Zayavki { get; set; }
        public System.DateTime Data { get; set; }
        public string Status { get; set; }
    }
}
